name: Daily Market Report

on:
  schedule:
    # This is set to 14:00 UTC (Which is 9:00 AM EST)
    - cron: '0 14 * * *'
  workflow_dispatch: # This adds a "Play" button so you can run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pandas yfinance

      - name: Run script
        env:
          CG_API_KEY: ${{ secrets.CG_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python crypto_report.py
